- name: Ensure hello-world path exists
  ansible.builtin.file:
    state: directory
    dest: hello-world/
    mode: '0755'

- name: Download remove.sh
  ansible.builtin.get_url:
    url: "{{ cleanup_command_url }}"
    dest: hello-world/
    mode: '0755'

