- name: Stop and remove the frontend application
  containers.podman.podman_container:
    name: frontend
    state: absent

- name: Stop and remove the backend application
  containers.podman.podman_container:
    name: backend
    state: absent
